# Generated by Django 4.0.3 on 2024-06-12 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c02',
            name='date',
        ),
    ]
